### ISSUE TITLE
modularmachinery-1.12.2-1.11.1 ⚔️ herodotusutils-1.0-build135

### ISSUE THREAD

**Issue by ChromaPIE** [ProjectHDS/HerodotusUtils#4]
CR: https://pastebin.com/9QqRPzJH

**Comment by friendlyhj** [comment]
正好我写完准备测试的时候发的 issue...

**Comment by ChromaPIE** [comment]
不行 https://pastebin.com/NtDtihup

**Comment by friendlyhj** [comment]
`	| LE    | modulardiversity                  | 1.10                 | Modular Diversity-1.10.jar                          | None                                     |`
和我无关了。
